const { ethers } = require("ethers");
require("dotenv").config();

// 1. The Provider: Determines HOW we talk to the blockchain.
// In production, process.env.POLYGON_URL will be an Alchemy or Infura node URL.
// For local testing, it defaults to your local Ganache network on port 8545.
const provider = new ethers.JsonRpcProvider(process.env.POLYGON_URL || "http://127.0.0.1:8545");

// 2. The Wallet: Determines WHO is talking to the blockchain.
// This is the backend's hidden automated wallet. It signs transactions securely.
// Ensure process.env.SERVER_PRIVATE_KEY is never exposed in client-side code!
const privateKey = process.env.SERVER_PRIVATE_KEY || "0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"; // Default dummy key
const wallet = new ethers.Wallet(privateKey, provider);

// 3. The Contract Interface (ABI)
// The ABI (Application Binary Interface) is a JSON map that tells Node.js
// exactly what functions (like `mintBatch` or `initiateTransfer`) exist on the contract.
let AmmunitionAssetABI = [];
try {
    // In a live Truffle project, this file is automatically generated when you run `truffle compile`.
    AmmunitionAssetABI = require("../../smart-contracts/build/contracts/AmmunitionAsset.json").abi;
} catch (error) {
    console.warn("⚠️ Warning: Could not find compiled smart contract ABI. Please run 'truffle compile' in the smart-contracts folder first.");
}

// 4. The Final Bridge
// We combine the Address, the ABI mapping, and the Signed Wallet.
const contractAddress = process.env.CONTRACT_ADDRESS || "0xYourDeployedContractAddress";
const ammunitionContract = new ethers.Contract(contractAddress, AmmunitionAssetABI, wallet);

module.exports = {
    provider,
    wallet,
    ammunitionContract
};
